on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.UBERSHMEKEL_ALT_TOKEN }}
      - uses: actions/cache@v2
      - run: python main.py
